version: '3.7'

services:
  db-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pocket-message"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
    networks:
    - pocket-message-networks
    ports:
      - '3306:3306'
    expose:
      - '3306'

  pocket_message-app:
    build: ./
    depends_on:
      - db-mysql
    environment:
      APIPort: ":8080"
      DB_ADDRESS: "db-mysql:3306"
      DB_NAME: "pocket_message"
    ports:
      - "80:8080"
    expose:
      - '80'
    networks:
      - pocket-message-networks

networks:
  pocket-message-networks